# Generated by Django 3.0.6 on 2020-05-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
